### ISSUE TITLE
Dark screen

### ISSUE THREAD

**Issue by potato-man123** [pthom/imgui_manual#13]
I am unable to view the website. All I see is a dark screen for some reason. Recently I installed Arch for performance issues with my old Debain. The manual worked great with my old debain but not now in Arch. In the web console I get these errors: 

```
TypeError: Cannot read properties of undefined (reading 'getParameter')
    at emscriptenWebGLGet (imgui_manual.js:1:172601)
    at _glGetIntegerv (imgui_manual.js:1:176291)
    at imgui_manual.wasm:0x6db46
    at imgui_manual.wasm:0x50cb3
    at imgui_manual.wasm:0x6dc40
    at imgui_manual.wasm:0x1173c
    at imgui_manual.js:1:28198
    at callMain (imgui_manual.js:1:278404)
    at doRun (imgui_manual.js:1:278877)
    at imgui_manual.js:1:279032  
```
what can I do to fix this? or how can I run the manual locally?

**Comment by pthom** [comment]
I'm sorry it's difficult to help you on my side because I cannot reproduce the issue. 

You should look at your drivers, Since the manual uses openGL.

May be look at  WebGL Report (https://webglreport.com/) to see what it says about your driver and update it if required.
